<?php
/**
 * @var \MODX\Revolution\modX $modx
 * @var array $namespace
 */

// Include autoloader generated by your composer
require_once $namespace['path'] . 'vendor/autoload.php';

if (!$modx->services->has('formprotection')) {
    // Register base class in the service container
    $modx->services->add('formprotection', function($c) use ($modx) {
        return new \FormProtection\FormProtection($modx);
    });

    // Load packages model, uncomment if you have DB tables
    //$modx->addPackage('FormProtection\Model', $namespace['path'] . 'src/', null, 'FormProtection\\');
}

// More about this file: https://docs.modx.com/3.x/en/extending-modx/namespaces#bootstrapping-services
